version: "3"
services:
  app:
    build:
     context: .
     dockerfile: docker/dockerfile-node
    volumes:
       - ./:/code
    working_dir: /code
    command: yarn serve
    environment:
      HOST: 0.0.0.0
      API: 'https://api.epaper.testingmachine.eu/'
    ports:
      - "3000:8080"
